name = "prepaid-orange-vod-oneshot-agent"
language = "rust"
type = "actor"
version = "0.1.0"

[actor]
claims = ["wasmcloud:keyvalue", "wasmcloud:builtin:logging", "wasmcloud:builtin:numbergen"]
call_alias = "agent/prepaid_orange_vod_oneshot"