[package]
name = "http-hello-world"
edition = "2021"
version = "0.1.0"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.30"
serde = { version = "1.0.209", features = ["derive"] }
o2o = "0.4.9"
serde_json = "1.0.127"
