swagger: "2.0"
info:
  version: "1.0.0"
  title: "WasmCloud Rating"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "weathered-mountain-8378.cosmonic.app"
tags:
- name: "Rating"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "https"
- "http"
paths:
  /usage/rating:
    post:
      tags:
      - "Rating"
      summary: "Rate user usage"
      description: ""
      operationId: "rateUsage"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Usage that needs to be rated"
        required: true
        schema:
          $ref: "#/definitions/RatingRequest"
      responses:
        "405":
          description: "Invalid input"
  
definitions:
  RatingRequest:
    type: "object"
    properties:
      customerId:
        type: "string"
      usage:
        type: "string"
      agentId:
        type: "string"
    xml:
      name: "RatingRequest"
  
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
        
        
        
        
        