openapi: 3.0.1
info:
  title: WasmCloud Rating
  version: 1.0.0
servers:
- url: ''
tags:
- name: Rating
  externalDocs:
    description: Find out more
    url: http://swagger.io
paths:
  /usage/rating:
    post:
      tags:
      - Rating
      summary: Rate party usage
      operationId: rateUsage
      requestBody:
        description: Usage that needs to be rated
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RatingRequest'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RatingResponse'
        400:
          description: Invalid username supplied
          content: {}
        404:
          description: User not found
          content: {}
        405:
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
  
  /party/{partyId}/offers/{vendor}:
    get:
      tags:
      - Inventory
      summary: Rate user usage
      operationId: getPartyOffers
      parameters:
        - in: path
          name: partyId
          schema:
            type: string
          required: true
          description: Alphnumeric ID of the party to get offers for
        - in: path
          name: vendor
          schema:
            type: string
          required: true
          description: Alphnumeric ID of the vendor to get offers subscribed by party
      responses:
        200:
          description: successful operation
          content: {}
        400:
          description: Invalid partyId or vendor supplied
          content: {}
        405:
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
components:
  schemas:
    RatingRequest:
      type: object
      properties:
        customerId:
          description: 'Party Id who is using the service'
          type: string
        usage:
          description: 'usage list'
          type: array
          items: 
            $ref: "#/components/schemas/UsageCharacteristic"
        agentId:
          description: "The agent id aka actor call alias, to be used as the rating agent for this request"
          type: string
      xml:
        name: RatingRequest
    UsageCharacteristic:
      type: object
      description: 'Describes usage characteristic of some product'
      properties:
        name:
          description: "Name of the usage characteristic"
          type: "string"
        value:
          description: "Value of the usage characteristic"
          type: "string"
        valueType:
          description: "Data type of the value of the usage characteristic"
          type: "string"
    RatingResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
