# This is a full example of how to run the rating-poc example. Using this example requires you to
# have WADM running: https://github.com/wasmCloud/wadm/tree/main/wadm and a host labeled with
# `app=rating-poc`. You can deploy this example with two simple commands:
#
# `wash app put wadm.yaml`
# `wash app deploy rating-poc 0.0.1`

apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: rating-poc
  annotations:
    version: v0.0.1
    description: "Distributed Rating POC"
spec:
  components:
    - name: api-gateway
      type: actor
      properties:
        image: ghcr.io/distributed-it-for-telco/distributed-rating-poc/api_gateway:0.1.0
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: linkdef
          properties:
            target: httpserver
            values:
              address: 0.0.0.0:8080

    - name: rating-coordinator
      type: actor
      properties:
        image: ghcr.io/distributed-it-for-telco/distributed-rating-poc/rating_coordinator:0.1.0
      traits:
        - type: spreadscaler
          properties:
            replicas: 1

    - name: httpserver
      type: capability
      properties:
        image: wasmcloud.azurecr.io/httpserver:0.16.2
        contract: wasmcloud:httpserver
      traits:
        - type: spreadscaler
          properties:
            replicas: 1

    - name: redis
      type: capability
      properties:
        image: wasmcloud.azurecr.io/kvredis:0.21.0
        contract: wasmcloud:keyvalue
      traits:
        - type: spreadscaler
          properties:
            replicas: 1