# This is a full example of how to run the rating-poc example. Using this example requires you to
# have WADM running: https://github.com/wasmCloud/wadm/tree/main/wadm and a host labeled with
# `app=rating-poc`. You can deploy this example with two simple commands:
#
# `wash app put wadm.yaml`
# `wash app deploy rating-poc 0.0.1`

apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: rating-poc
  annotations:
    version: v0.0.1
    description: "Distributed Rating POC"
spec:
  components:
    - name: api-gateway
      type: actor
      properties:
        image: ghcr.io/distributed-it-for-telco/distributed-rating-poc/api_gateway@sha256:e2d6cb1933ab3166e2b2ffc74ec0d84efe388171cab3d4279a76d62eada6214f
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
            spread:
              - name: clinicapp
                requirements:
                  # name: stargate_host_22001
                  stargate: "true"

        - type: linkdef
          properties:
            target: httpserver
            values:
              address: 0.0.0.0:8080

    # - name: httpserver
    #   type: capability
    #   properties:
    #     image: wasmcloud.azurecr.io/httpserver:0.16.2
    #     contract: wasmcloud:httpserver
    #   traits:
    #     - type: spreadscaler
    #       properties:
    #         replicas: 1
    #         spread:
    #           - name: httpserverspread
    #             requirements:
    #               name: petclinic

    # - name: postgres
    #   type: capability
    #   properties:
    #     image: wasmcloud.azurecr.io/sqldb-postgres:0.3.1
    #     contract: wasmcloud:sqldb
    #   traits:
    #     - type: spreadscaler
    #       properties:
    #         replicas: 1
    #         spread:
    #           - name: postgresspread
    #             requirements:
    #               app: petclinic
