name = "PrepaidOrangeVodOneshotCQRSAgent"
language = "rust"
type = "actor"
version = "0.1.0"

[actor]
claims = ["wasmcloud:keyvalue", "wasmcloud:builtin:logging", "wasmcloud:builtin:numbergen", "wasmcloud:messaging"]
call_alias = "agent/prepaid_orange_vod_oneshot_cqrs"