package orange:ratingcoordinator;

interface ratingcoordinator{
  use orange:rating/types.{rating-request,rating-response};
  handle-rating-process: func(request: rating-request, headers: list<tuple<string,list<u8>>>) -> rating-response;
}

world rating-coordinator-world {
  import orange:rating/ratingagent;
  import wasi:logging/logging@0.1.0-draft; 
  import wasmcloud:bus/lattice@1.0.0;

  export ratingcoordinator;
}
