interface types{

  use wasi:http/types@0.2.0.{fields};
  use orange:rating/types.{rating-request};

  record rating-process-request{
  rating-request: rating-request,
  headers: fields
} 
return-procees-request: func() -> rating-process-request;

}