package orange:video-provider-usage-collector;

world video-provider-usage-collector-world {
   import wasi:keyvalue/atomics@0.2.0-draft; 
   import wasi:keyvalue/store@0.2.0-draft; 
   import wasi:logging/logging@0.1.0-draft; 

   export orange:usagecollector/usagecollector;
}
