package wasmcloud:hello;

world api-gateway-world {
  import orange:commons/mappers;
  import orange:commons/types;
  import orange:rating/ratingagent;
  import orange:ratingcoordinator/ratingcoordinator;
  import wasi:logging/logging@0.1.0-draft; 
  import wasmcloud:bus/lattice@1.0.0;
  
  export wasi:http/incoming-handler@0.2.0;
}
