interface error-types{
    record validation-error{
        message: string
    }
    record usage-error{
        message: string
    }
    
    record other-error{
        message: string
    }

    variant generic-error{
        validation(validation-error),
        usage(usage-error),
        other(other-error)
    }
}