package orange:commons;

interface mappers{
    use types.{rating-request};
    rating-request-to-string: func(request: rating-request) -> string;
    string-to-rating-request: func(value: string) -> rating-request;
}