package orange:commons;

interface commons {
  use types.{balance, usage-proof-request};
  create-balance: func(count: f32, unit: string, party-id: string) -> balance;
  generate-rating-proof: func(request: usage-proof-request) -> string;
}

world commons-world {
  export commons;
}
