package orange:metaverse-ratingagent;

world metaverse-rating {
    import orange:balancemanager/balancemanager;
    import wasi:logging/logging@0.1.0-draft;  

    export orange:rating/ratingagent;
}