
interface balance-manager {
    deposit: func(request: deposit-request) -> balance;

    record deposit-request {
        amount: f32,
        customer-id: string,
        offer-id: string
    }

    record balance {
        party-id: string,
        balance-characteristic: balance-characteristic
    }

    record balance-characteristic {
        unit: string,
        count: f32
    }
}