apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: rating-agent
spec:
  components:
    - name: rating-agent
      type: component
      properties:
        image: file://./build/rating_agent_s.wasm
      traits:
        # Govern the spread/scheduling of the component
        - type: spreadscaler
          properties:
            instances: 1

    
