name: Build and check rating-agents/orange-rating-agent actor
on:
  pull_request:
    branches: [main]
    paths:
      - "rating-agents/orange-rating-agent/src/**"
      - "rating-agents/orange-rating-agent/Cargo.*"
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add wasm32-unknown-unknown
        run: rustup target add wasm32-unknown-unknown
      - name: Check formatting
        run: cargo fmt -- --check
        shell: bash
      - name: Build actor
        run: cargo build
      - name: Check lints with clippy
        run: |
          rustup component add clippy
          cargo clippy
      # Once you've written unit tests for the rating-agents/orange-rating-agent actor, you can uncomment
      # the two lines below to automatically run tests
      # - name: Test actor
      #   run: cargo test --target x86_64-unknown-linux-gnu -- --nocapture
