name: Build and check balance-management/kv-balance-manager actor
on:
  pull_request:
    branches: [main]
    paths:
      - "balance-management/kv-balance-manager/src/**"
      - "balance-management/kv-balance-manager/Cargo.*"
env:
  working-directory: "balance-management/kv-balance-manager"
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add wasm32-unknown-unknown
        run: rustup target add wasm32-unknown-unknown
      - name: Check formatting
        working-directory: ${{ env.working-directory }}
        run: cargo fmt -- --check
      - name: Build actor
        working-directory: ${{ env.working-directory }}
        run: cargo build
      - name: Check lints with clippy
        working-directory: ${{ env.working-directory }}
        run: |
          rustup component add clippy
          cargo clippy
      # Once you've written unit tests for the api-gateway actor, you can uncomment
      # the two lines below to automatically run tests
      # - name: Test actor
      #   run: cargo test --target x86_64-unknown-linux-gnu -- --nocapture
